import { Inter } from "next/font/google";
import "./globals.css";
import { ChatwootLoader, CrispChatLoader, PosthogLoader, TawkToLoader } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <PosthogLoader>
        <body className={`dark ${inter.className}`}>{children}</body>
      </PosthogLoader>
      {/* <CrispChatLoader /> */}
      {/* <TawkToLoader /> */}
      <ChatwootLoader />
    </html>
  );
}
